[package]
name = "tik-dfpwm"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.156"}
reqwest = { version = "0.11.17", features = ["json", "cookies"] }
tokio = { version = "1.26.0", features = ["full"] }