name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build
        run: cargo build --release

      - name: Upload Built Binary
        uses: actions/upload-artifact@v3.2.0-node20
        with:
          name: built-binary
          path: |
            target/release
          if-no-files-found: error
