name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Make envfile
      run: |
        touch .env
        echo SESSION_ID=${{ secrets.SESSION_ID }} >> .env
        echo API_URL=${{ secrets.API_URL }} >> .env
        echo INTERFACE=${{ secrets.INTERFACE }} >> .env
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
